#!/bin/sh
# Arguments are:
# 1 - COMPILE statement
# 2 - base of module name (no extension)
# 3 - source file name
#echo $2 $3
if [ -f $2.mod ]; then
  mkdir $2.tmp
  #echo $1 -module $2.tmp $3
  $1 -module $2.tmp/ $3
  #cmp -s $2.tmp/$2.mod $2.mod
#  for module in `ls $2.tmp`
#  do
  if [ `diff -a $2.tmp/$2.mod $2.mod | wc -l` != "4" ]; then
#    if [ `diff -a $2.tmp/$module $module | wc -l` != "4" ]; then
    echo "Using new module file"
#    mv $2.tmp/$2.mod $2.mod
    mv $2.tmp/$2.mod $2.mod    
  fi
#  done 
  rm -rf $2.tmp
else
  $1 $3
fi
